travis:
  secure:
    BINSTAR_TOKEN: vAjrwOIhsgwg11rcZurRaV1OuFUUA47kyioT5di4DSHCKBj+XD3KxmYXnlkUeyH406gqeg/SJHRwnjs7FsO6HzskN0IQmKi8m1wigATpElWKJlFknAluZYyOx8Yqkq0dF2gixeUdrpX5lWPWCi0+vwOaQUiWCu9CVSLw6WBghIxXS2AxRWVoH/co1F3AOr8zfcBorqLwzTuk2x0w8xa3qnzdn9fkttnxCYgGZqDsMwfcvDkksFlJismgcqCMkZw7QWW8Nl0EWUXQyDH/RY7VSAAkoz+xzUSARjy2ogyIzrN1jfc0k7e2UaqsYiW48EGi1K4o3TMS9ZF9cr+TbAK42dMMx3AKdpoUuGGBiYJgzH2MUlXEKYcfoLJJePWX189pT6WabB3RrjBdBZAJycAbTINcYj0VdHfjmEK9/hnAdk4etsGjXHzApz62HDLzdnpGJgg0y4zgvvMw3dGkLhbsNFQfytbsnPxSGVaVBcs6LbHHSxN6sv/5ZU7mZg/EPXcGh6kbKqULdNN2TpcdAAlS+fLaBY5u8Roxw1oDvqkbNL8bq0P7rrlSzvtk6w+MrrSljwAjEb4Pqq1Xu7SRNGH8oc2ZlwJraUKDt91rriUFsWYKF7G4hq3vSzEYJEqA++Aa+4lyo9t9pn8yQQ1h1jd0ZWip2J05pSAmRYLSVQsF+Vo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  targets:
  - [conda-forge, dev]
conda_forge_output_validation: true
